### ISSUE TITLE
Could not find net.minecraftforge:forgeSrc:1.8.9-11.15.1.2318-1.8.9 when attempting to build

### ISSUE THREAD

**Issue by Ikethepro18** [TGWaffles/TheExoticsMod#48]
I've tried building the mod but when I do I get a very quick error telling me that it can't find forgeSrc:1.8.9-11.15.1.2318-1.8.9 and then lists all the locations it's tried to find it

Below is an image of the full attempted build
![image](https://github.com/TGWaffles/iTEM/assets/73065710/173fe0bf-9656-437d-8567-22b4994c5ce8)

**Comment by Orenico10** [comment]
> I've tried building the mod but when I do I get a very quick error telling me that it can't find forgeSrc:1.8.9-11.15.1.2318-1.8.9 and then lists all the locations it's tried to find it
> 
> Below is an image of the full attempted build
> ![image](https://github.com/TGWaffles/iTEM/assets/73065710/173fe0bf-9656-437d-8567-22b4994c5ce8)
> 

That's interesting, forge 1.8.9:2318 is the latest version of forge for 1.8.9, are you using any proxy or anything that blocks your connection?

Edit: if you just want to use the mod you can download it from the discord that is linked in the readme.md, no need to build it yourself

**Comment by Ikethepro18** [comment]
No proxies or VPNs o anything, just a clean connection. Manually visiting each site it listed does give a 404 rather than something like a 403

**Comment by Orenico10** [comment]
> No proxies or VPNs o anything, just a clean connection. Manually visiting each site it listed does give a 404 rather than something like a 403

Could you share some more data about this issue so that I can try to find a solution?

What OS and distro are you using?
What Java version are you using?

And if you could retrace your steps that'd be helpful.

**Comment by Ikethepro18** [comment]
Of course

- Running Windows 11 23H2 22631.3737
- Building using Java 1.8.0_371 (I believe it's an Oracle distro)

I began with cloning with git clone to download the repo. Then I installed Protobuf using `winget install Google.Protobuf` and ran the 2 commands on the README in the iTEM directory. Then I ran `./gradlew.bat build` which did some stuff and then failed. Subsequent attempts to build last no more than 10 seconds and give the same error

**Comment by Orenico10** [comment]
Ok, I see where the issue is.
When you want to use Gradle for Forge mod development you need to run a Gradle script before trying to compile the Java project.

If you are using an IDE like IntelliJ IDEA you can click on the little Gradle elephant on the right and select the script.
![image](https://github.com/TGWaffles/iTEM/assets/78265216/f1eb6406-5da6-47ae-9b10-dc999181ef29)

if you're not using an IDE try running this:
```ps
./gradlew setupdecompworkspace
```
and then you run:
```ps
./gradlew build
```
like you initially tried.

If you just want to use the mod and you're not trying to add features/develop the mod you have 2 options for downloading a pre-built JAR:

1. You can download it from our CI tool [here](https://ci.thom.club/job/TheExoticsMod/job/master/lastSuccessfulBuild/artifact/build/libs/)
2. You can download it from our discord [here](https://discord.com/invite/item-932106421338779709)

Edit: Regardless, you won't need to install Protobuf or run the commands in the README.md file, these commands are for when Thomas (The mod's creator) decides to change some communication between the mod and the server (Protobuf is a binary serializer for web communications).

**Comment by Ikethepro18** [comment]
Seems to have worked. I ran the commands in the README (because I hadn't spotted you said not to) and the build failed but doing it all again without the commands worked fine. I was just trying to use the mod but it's nice to build it yourself so thanks for the help
